{"name": "Проверка ошибки при попытке получения заказа с несуществующим номером", "status": "passed", "steps": [{"name": "Отправляем запрос GET на получение заказа по его номеру", "status": "passed", "parameters": [{"name": "id_track", "value": "1308142"}], "start": 1715459067024, "stop": 1715459067798}], "start": 1715459067023, "stop": 1715459067805, "uuid": "cfa7c8f9-c0d8-403b-9fdc-bd9990e2cb7a", "historyId": "aa52b7ecbcccd3f41ca336b3a91aad58", "testCaseId": "aa52b7ecbcccd3f41ca336b3a91aad58", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_by_invalid_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "Asus-ПК"}, {"name": "thread", "value": "5600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}