{"name": "Проверка ошибки при попытке получения заказа с несуществующим номером", "status": "passed", "steps": [{"name": "Отправляем запрос GET на получение заказа по его номеру", "status": "passed", "parameters": [{"name": "id_track", "value": "1172427"}], "start": 1715196952641, "stop": 1715196953498}], "start": 1715196952641, "stop": 1715196953501, "uuid": "6f0877b0-c255-433e-8e08-06483683229a", "historyId": "aa52b7ecbcccd3f41ca336b3a91aad58", "testCaseId": "aa52b7ecbcccd3f41ca336b3a91aad58", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_by_invalid_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "Asus-ПК"}, {"name": "thread", "value": "28064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}